xss_whitelist:
  - admin.super
xss_enabled:
  on_events: true
  invalid_protocols: true
  moz_binding: true
  html_inline_styles: true
  dangerous_tags: true
xss_invalid_protocols:
  - javascript
  - livescript
  - vbscript
  - mocha
  - feed
  - data
xss_dangerous_tags:
  - applet
  - meta
  - xml
  - blink
  - link
  - embed
  - object
  - iframe
  - frame
  - frameset
  - ilayer
  - layer
  - bgsound
  - title
  - base
  - style
  - script
uploads_dangerous_extensions:
  - php
  - html
  - htm
  - js
  - exe
salt: bZS0OH2a6xmynJ
